server:
  port: 8673
zuul:
  routes:
    noteapplication:
      path: /noteservice/**
      serviceId: noteservice
    userapplication:
      path: /userservice/**
      serviceId: userservice
  host:
    socket-timeout-millis: 60000
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: zuul
    
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 600000

  
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false