spring : 
  application : 
      name : eurekaserver

server:
    port : 8761

eureka :
    client : 
      serviceUrl : 
        defaultZone : http://127.0.0.1:8761/eureka/
      register-with-eureka : false
      fetch-registry : false
    instance:
       lease-renewal-interval-in-seconds: 30