spring:
  application:
    name: spring-cloud-ribbon
server:
  port: 8888
userservice:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9999
    ServerListRefreshInterval: 15000